### ISSUE TITLE
"CircuitPython: Update All Libraries" fails

### ISSUE THREAD

**Issue by RobCranfill** [wmerkens/vscode-circuitpython#11]
**Describe the bug**
Executing the command "CircuitPython: Update All Libraries"  gives an error (see screenshot). 

**To Reproduce**
1. press <ctrl><shift>P 
2.  typing enough to find that command)
3. See error below

**Expected behavior**
Actually, I'm not sure - I haven't used this command before! Something like Circup's output?

**Screenshots**
![image](https://github.com/user-attachments/assets/2dbc3495-78a2-4469-b486-a8bc34d085e3)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 24.10

**Additional context**
Plugin version [0.2.8]

VSCode info:
  Version: 1.95.3
  Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
  Date: 2024-11-13T14:50:04.152Z
  Electron: 32.2.1
  ElectronBuildId: 10427718
  Chromium: 128.0.6613.186
  Node.js: 20.18.0
  V8: 12.8.374.38-electron.0
  OS: Linux x64 6.11.0-9-generic snap

I *think* this is the (or  *a*) pertinent log entry from /home/rob/.config/Code/logs/20241209T101407/window1/exthost/exthost.log :

```
2024-12-09 14:38:39.311 [error] Error: ENOENT: no such file or directory, lstat '/home/rob/.config/Code/User/globalStorage/wmerkens.vscode-circuitpython-v2/bundle/20241206/adafruit-circuitpython-bundle-9.x-mpy-20241206/lib/adafruit_bme280'
	at lstatSync (node:fs:1643:25)
	at t.lstatSync (node:electron/js2c/node_init:2:4536)
	at Object.lstatSync (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/node_modules/graceful-fs/polyfills.js:318:34)
	at statFunc (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/node_modules/fs-extra/lib/util/stat.js:24:20)
	at getStatsSync (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/node_modules/fs-extra/lib/util/stat.js:25:19)
	at Object.checkPathsSync (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/node_modules/fs-extra/lib/util/stat.js:64:33)
	at Object.copySync (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/node_modules/fs-extra/lib/copy/copy-sync.js:27:38)
	at LibraryQP.install (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/out/librarymanager/libraryManager.js:93:22)
	at LibraryQP.update (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/out/librarymanager/libraryManager.js:100:14)
	at LibraryQP.onClick (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/out/librarymanager/libraryManager.js:83:22)
	at /home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/out/librarymanager/libraryManager.js:174:15
	at Array.forEach (<anonymous>)
	at LibraryManager.update (/home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/out/librarymanager/libraryManager.js:173:17)
	at /home/rob/.vscode/extensions/wmerkens.vscode-circuitpython-v2-0.2.8/out/container.js:64:75
	at Y0.h (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
	at Y0.$executeContributedCommand (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:33683)
	at py.S (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
	at py.Q (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
	at py.M (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
	at py.L (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111285)
	at mh.value (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
	at D.B (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at D.fire (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at mh.value (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)
	at D.B (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at D.fire (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at MessagePortMain.<anonymous> (file:///snap/code/176/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11592)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) circuitpython.library.update {"value":"wmerkens.vscode-circuitpython-v2","_lower":"wmerkens.vscode-circuitpython-v2"}

```

**Comment by wmerkens** [comment]
Ok, this came from when the bundle was unpacked; the NPM package that did the unpacking was failing, so I have replaced it with a different NPM module
